Assign "x" (Const (I 1))
Assign "y" (Const (I 2))
Fork (Synchronised (Assign "y" (Const (I 42))))
Assign "y" (Add (Var "y") (Const (I 3)))
Assign "y" (Add (Var "y") (Const (I 3)))
Assign "y" (Add (Var "y") (Const (I 3)))
Assign "x" (Sub (Var "x") (Const (I 2)))
Print (Var "x")
Print (Var "y")
